export const USER_SESSION_INIT = "USER_SESSION_INIT";
export const USER_SESSION_UPDATE = "USER_SESSION_UPDATE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CONNECT_SOCKET_REQUEST = "ESTABLISH_SOCKET_REQUEST";
export const CONNECT_SOCKET_ERRORED = "ESTABLISH_SOCKET_ERRORED";
export const CONNECT_SOCKET_SUCCESS = "ESTABLISH_SOCKET_SUCCESS";

export const UPDATE_CLIENT_ROOM = "UPDATE_CLIENT_ROOM";
export const UPDATE_CLIENT_ROOM_CHAT = "UPDATE_CLIENT_ROOM_CHAT";
export const GAME_UPDATE = "GAME_UPDATE";

export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";

export const INIT_CLIENT = "INIT_CLIENT";
export const INIT_GAME = "INIT_GAME";
