export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_ERRORED = 'GET_MOVIES_ERRORED'

export const SET_REQUEST_IN_PROGRESS = 'SET_REQUEST_IN_PROGRESS';