export const forumRequests: {
  FETCH_POSTS_BY_RECENT: 'FETCH_POSTS_BY_RECENT';
  FETCH_POSTS_BY_PAGE: 'FETCH_POSTS_BY_PAGE';
  FETCH_POST_BY_ID: 'FETCH_POST_BY_ID';
} = {
  FETCH_POSTS_BY_RECENT: 'FETCH_POSTS_BY_RECENT',
  FETCH_POSTS_BY_PAGE: 'FETCH_POSTS_BY_PAGE',
  FETCH_POST_BY_ID: 'FETCH_POST_BY_ID'
};
