export const forumRequests: {
  FETCH_POSTS_BY_RECENT: 'FETCH_POSTS_BY_RECENT';
  FETCH_POSTS_BY_PAGE: 'FETCH_POSTS_BY_PAGE';
} = {
  FETCH_POSTS_BY_RECENT: 'FETCH_POSTS_BY_RECENT',
  FETCH_POSTS_BY_PAGE: 'FETCH_POSTS_BY_PAGE'
};
